### ISSUE TITLE
ISO country codes

### ISSUE THREAD

**Issue by DanielRobertNicoud** [CoronaWhy/task-geo#11]
*In the output of the API version of the code the country code is missing.

*Country codes in the data are not ISO (see ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-countries.txt eg CH should be Switzerland, it is for China instead).

**Comment by ManuelAlvarezC** [comment]
Hi @DanielRobertNicoud.

This is the point 1 mentioned in the issue #8. Please close this issue as is redundant.

Thanks
