### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ManuelAlvarezC** [CoronaWhy/task-geo#14]
- Specify No one-hot encodes on data model.
- Update NOAA notebook
- Add data sources  on AUTHORS
- Add specification for  metadata.json and dataset description
- Specify module structure for data sources.
- Restructure documentation.
- Add basic user guide and unified easy access to individual datasources 
- Improve contributing guide.

**Comment by JuanCalvoFerrandiz** [comment]
Hi! Juan, data scientist from the Viz team.
I'm having difficulties with the installation for being able to use the library: 
`(coronawhy) C:\Users\juanc>git clone git@github.com:CoronaWhy/task-geo.git
Cloning into 'task-geo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

I thought that for cloning I should use this command: 
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository

**Comment by ManuelAlvarezC** [comment]
Hi @JuanCalvoFerrandiz  and thanks for the feedback, I will upload the github link in the documentation to the https one.

Can you please specify with python version are you using? 
Also, please try with just `make install`, as the current installation in the readme is focused for developers, will change that too.

Also, please, next time, don't send an screenshot of a text screen, copy and paste the code, is easier to work this way.
