### ISSUE TITLE
Add a datasource for COVID cases in Spain

### ISSUE THREAD

**Issue by ManuelAlvarezC** [CoronaWhy/task-geo#17]
## Description 

Create a datasource using [this](https://covid19.isciii.es/resources/serie_historica_acumulados.csv)

**Comment by ManuelAlvarezC** [comment]
> On task-geo Brian Vacha wrote:
> 
> > Ok, I'm back to working Spain data. I have data in this form:
> > ```
> >   ccaa-iso-code        date  cases  hospitalized  UCI  deceased  recovered
> > 0            AN  20/02/2020    NaN           NaN  NaN       NaN        NaN
> > 1            AR  20/02/2020    NaN           NaN  NaN       NaN        NaN
> > 2            AS  20/02/2020    NaN           NaN  NaN       NaN        NaN
> > 3            IB  20/02/2020    1.0           NaN  NaN       NaN        NaN
> > 4            CN  20/02/2020    1.0           NaN  NaN       NaN        NaN
> > ```
> > 
> > 
> > First, does this look worthwhile? It's at the region level. Second, given https://coronawhy.github.io/task-geo/data_model.html, would you say the target format would be:
> > ```
> > date       iso-3166-1-alpha-3 region latitude  longitude cases hospitalized uci deceased recovered
> > 2020-01-01 Spain              AN     40.416775 -3.703790 1     0            1   1        1
> > ```

You are almost right, the only thing is that `date` column should be after geographical columns

**Comment by JuanCalvoFerrandiz** [comment]
https://public.opendatasoft.com/explore/dataset/comunidades-autonomas-espanolas/table/?sort=comunidade_autonoma

Data link for adding Geo Point and Geo Shape :) If not, I will do it later in possible  Viz transformations.

Anyway, any code that I do for exploration in Viz I will share it in comments like this in the pertinent issue if you think it is ok.
