### ISSUE TITLE
Problems installing the repository on Windows

### ISSUE THREAD

**Issue by ManuelAlvarezC** [CoronaWhy/task-geo#21]
Hi! Juan, data scientist from the Viz team.

**1 ERROR:**
I'm having difficulties with the installation for being able to use the library: 
> (coronawhy) C:\Users\juanc>git clone git@github.com:CoronaWhy/task-geo.git
> Cloning into 'task-geo'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

I thought that for cloning I should use this command: 
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository

**UPDATE: 2 ERROR:** 
Using 
>"git clone https://github.com/CoronaWhy/task-geo.git" 

I have being able to install, but had the next errors:

![Capture678](https://user-images.githubusercontent.com/20303036/78136038-392ab900-7423-11ea-9d71-797b61023c42.JPG)

_Originally posted by @JuanCalvoFerrandiz in https://github.com/CoronaWhy/task-geo/issues/14#issuecomment-607194023_

**Comment by ManuelAlvarezC** [comment]
Hi @JuanCalvoFerrandiz  and thanks for the feedback, I will upload the github link in the documentation to the https one.

Can you please specify with python version are you using? 
Also, please try with just `make install`, as the current installation in the readme is focused for developers, will change that too.

Also, please, next time, don't send an screenshot of a text screen, copy and paste the code, is easier to work this way.

**Comment by JuanCalvoFerrandiz** [comment]
Hi @ManuelAlvarezC . Thanks for your help. As we spoke:
- Python 3.7
- Tried with `make install`. Same error: 

>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\juanc\Anaconda3\envs\coronawhy\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\juanc\\Desktop\\01 JUAN CALVO\\01 BIG DATA\\01 PROYECTOS\\COVID-19\\CODE\\REPOSITORIES\\task-geo\\setup.py'"'"'; __file__='"'"'C:\\Users\\juanc\\Desktop\\01 JUAN CALVO\\01 BIG DATA\\01 PROYECTOS\\COVID-19\\CODE\\REPOSITORIES\\task-geo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
>          cwd: C:\Users\juanc\Desktop\01 JUAN CALVO\01 BIG DATA\01 PROYECTOS\COVID-19\CODE\REPOSITORIES\task-geo\
>     Complete output (7 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\juanc\Desktop\01 JUAN CALVO\01 BIG DATA\01 PROYECTOS\COVID-19\CODE\REPOSITORIES\task-geo\setup.py", line 9, in <module>
>         readme = readme_file.read()
>       File "C:\Users\juanc\Anaconda3\envs\coronawhy\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 193: character maps to <undefined>
>     ----------------------------------------

> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I have tried to track de error and it seems to have something to be with the encoding of `readme_file`.  Could be? I'm blocked with this issue. Any help is welcome.

https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character

**Comment by normtak** [comment]
Hi.
You could try:

> git checkout --track -b stable

**Comment by JuanCalvoFerrandiz** [comment]
Thanks four your interest @normtak.

I have tried with `git checkout master` and `git checkout --track -b stable`, and either in the master, or in the new branch I create name "stable" with your command, doesn't work the installation.

**Comment by ManuelAlvarezC** [comment]
The solution is simple:

On lines 9 and 12 of `setup.py` the `open` should be:

```python
with open(filename, encoding='utf-8') as file:
```

Will fix it ASAP

**Comment by normtak** [comment]
I had some issues with `make install` on Windows, so I decided to do the installation using Windows Subsystem for Linux.

**Comment by ManuelAlvarezC** [comment]
Hi @normtak!

Can you link the guideline you used to do so, and list any problem you found? This may be helpful for other users having similar problems.

Thanks!
