### ISSUE TITLE
Granular data - France

### ISSUE THREAD

**Issue by oussamanaji** [CoronaWhy/task-geo#24]
Main dataset : (Confirmed cases/recovering/recovered/deaths at department and region level)
https://www.data.gouv.fr/fr/datasets/chiffres-cles-concernant-lepidemie-de-covid19-en-france/ 

Nationwide tests data available:
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/documents/bulletin-national/covid-19-point-epidemiologique-du-10-mars-2020
https://www.santepubliquefrance.fr/maladies-et-traumatismes/maladies-et-infections-respiratoires/infection-a-coronavirus/documents/bulletin-national/covid-19-point-epidemiologique-du-15-mars-2020

Current status: Working on cleaning the aggregated data in an adequate format.

**Comment by jmague** [comment]
I'd be happy to contribute!

**Comment by ManuelAlvarezC** [comment]
Please, @oussamanaji, be careful when linking issues on your repo, you closed this one when merging the one on your fork
