### ISSUE TITLE
Error when requesting Spain temperatures data: noaa_api("SP",start_date,end_Date)

### ISSUE THREAD

**Issue by JuanCalvoFerrandiz** [CoronaWhy/task-geo#27]
**Describe the bug**
When requesting data of Spain I have the following error:

**Expected behavior**
Having back the dataset of Spain in the selected range of dates. It works perfectly well with France.

**Screenshots**

> data = noaa_api(countries, start_date, end_date)
>    ...:print(data)
>    ...:
> INFO:root:Requesting data for SP
> DEBUG:root:Making request 0 / 11
> DEBUG:root:Making request 1 / 11
> DEBUG:root:Making request 2 / 11
> DEBUG:root:Making request 3 / 11
> DEBUG:root:Making request 4 / 11
> DEBUG:root:Making request 5 / 11
> DEBUG:root:Making request 6 / 11
> DEBUG:root:Making request 7 / 11
> DEBUG:root:Making request 8 / 11
> DEBUG:root:Making request 9 / 11
> DEBUG:root:Making request 10 / 11
> DEBUG:root:Making request 11 / 11
> Traceback (most recent call last):
>   File "C:\Users\juanc\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-19-4fc4c4b9f545>", line 1, in <module>
>     data = noaa_api(countries, start_date, end_date)
>   File "C:/Users/juanc/Desktop/01 JUAN CALVO/01 BIG DATA/01 PROYECTOS/COVID-19/CODE/REPOSITORIES/task-geo-master\task_geo\data_sources\noaa\__init__.py", line 6, in noaa_api
>     raw = noaa_api_connector(countries, start_date, end_date)
>   File "C:/Users/juanc/Desktop/01 JUAN CALVO/01 BIG DATA/01 PROYECTOS/COVID-19/CODE/REPOSITORIES/task-geo-master\task_geo\data_sources\noaa\api_connector.py", line 142, in noaa_api_connector
>     return data[columns]
>   File "C:\Users\juanc\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2806, in __getitem__
>     indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
>   File "C:\Users\juanc\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1551, in _get_listlike_indexer
>     keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
>   File "C:\Users\juanc\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1644, in _validate_read_indexer
>     raise KeyError(f"{not_found} not in index")
> KeyError: "['SNWD'] not in index"

**Desktop (please complete the following information):**
 -  Windows
 - Chrome

**Comment by ManuelAlvarezC** [comment]
I've been able to replicate it, fix it ASAP.
