### ISSUE TITLE
Add Alpha 3 ISO to Country Map in commons

### ISSUE THREAD

**Issue by ilovechai** [CoronaWhy/task-geo#42]
### Description

Trello card : Add Alpha3 ISO to Country Map in commons

Currently the (commons)[https://github.com/CoronaWhy/task-geo/blob/master/task_geo/common/country_codes.py] has only FIPS and Alpha2 ISO codes to country MAPs.
We would also require Alpha3 ISO code to Country MAP
https://www.iso.org/obp/ui/#search

**Comment by cryptox31** [comment]
I added a iso2 to iso3 map and iso3 to iso2 map in the commons for everyone to use it.
