### ISSUE TITLE
Wrong "aggregate" value in Spain country rows (should be "country" instead of "state")

### ISSUE THREAD

**Issue by JuanCalvoFerrandiz** [CoronaWhy/task-geo#44]
* Commit SHA:
commit c4af4d71d781ac9fd204713b41cd79650519497c (HEAD -> master, origin/master, origin/HEAD)
Merge: f23824d 3de7d90
Author: Manuel Alvarez Campo <manuel@pythiac.com>
Date:   Sat Apr 4 13:48:16 2020 +0200

    Merge pull request #35 from shaikh-raj/master

    Adding metadata for CDS datasource
* Python version:3.7
* Operating System:Windows
* Data source: cds

### Description
Wrong "aggregate" value in Spain country rows (should be "country" instead of "state")

Code I use to change in exploration phase the error:
`data_cds.loc[(data_cds["country"] == "Spain") & (data_cds["state"].isnull()), "aggregate"] = "country"`

By the way, despite the normal little mistakes; great job of the api!

**Comment by ManuelAlvarezC** [comment]
Thanks @JuanCalvoFerrandiz  for another detailed bug report.

I have checked and will fix it soon!
