### ISSUE TITLE
Add option on NOAA datasource to aggregate by country and date

### ISSUE THREAD

**Issue by ManuelAlvarezC** [CoronaWhy/task-geo#51]
### Description
On the noaa_api data source: I need for the VIZ 1:
a) Average per country (1 value for each day and country) of average temperature
b) Average per country (1 value for each day and country) of average min temperature
c) Average per country (1 value for each day and country) of average max temperature
Trello card : https://trello.com/c/iJdSZPxs

**Comment by DanielRobertNicoud** [comment]
Given the structure of the data from NOAA, this would either be very complex or methodologically very bad. Closing the issue.

**Comment by ManuelAlvarezC** [comment]
After a discussion with Daniel we decided to change the methodology, instead of providing averages, we will only provide: 
- The minimum for the min temperatures, that is, the absolute minimum
- The maximum for the max temperatures, that is, the absolute maximum.
