### ISSUE TITLE
Create datapackage.json generator

### ISSUE THREAD

**Issue by ilovechai** [CoronaWhy/task-geo#66]
### Description

Trello card : https://trello.com/c/ltFftxrT/129-improve-github-workflow

**Comment by ManuelAlvarezC** [comment]
Hi @cryptox31.

After seeing your submission I see that there was a misunderstanding about what the datapackage.json generator should do.

The idea is to have a function with a prototype:

``` python
def generate_datapackage(data_source, save_file=False, file_path=None, *args, **kwargs):
    """Generate the scaffolding for datapackage.json.

    This function will always return a dictionary with the generated datapackage.json, but can also
    save it if its provided with `save_file=True` and `file_path` arguments.

    After running this function, some fields must be filled by hand

    Arguments:
        data_source(callable): Data source to generate datapackage to.
        save_file(bool): Wheter to save the file or not.
        file_path(str): Path to save the file.

    Returns:
        dict
    """
```

That recieves the data source and its positional and keyword arguments, and by executing it and inspection the data_source and its output fulfill most of the `datapackage.json` as we specified in the documentation.

Some of the things that can be infered are:

- **tags**: You can split the name of the `__module__` of the data source and take everything after `data_source` as tags: `task_geo.data_sources.demographics.us_census` -> `['demographics', 'us_census']`
- **Schema and fields**: By running the data source and then iterating over its `output.dtypes`, you can fill the `resources.schema.fields` list. 
- **url**: By parsing the data_source or module `__doc__` for a line containing `http`

Also, create the missing fields and populate them with something like : `XXXX TO BE FILLED XXXX`,so our developers know they have to do it by hand.

Two things to bear in mind are:
1. This datapackage generator is to be used for our developers to provide a first version of the datapackage, there are things that we can't know by inspection and must be filled by hand.

2. This is not the final version for the datapackage.json, as when the data source is executed in the automatic uploading of datasets, more fields will be added automatically ( like id, timestamps for creation and first version, etc, etc)

I hope this clarifies the scope and purpose of this task, if you still have any doubt, please don't hesistate to reply me below.
